### ISSUE TITLE
VPN disconnects and reconnects every ~15 minutes

### ISSUE THREAD

**Issue by SkyRexHUN** [AdguardTeam/AdGuardVPNForWindows#262]
![vpnreconnects](https://user-images.githubusercontent.com/92554890/167250406-4b9d1d51-951f-4beb-a21d-e36640d451a3.png)
As you can see on the attached picture, there are frequent connection interrupts and reconnects.

**Comment by SkyRexHUN** [comment]
Could you specify „sleep mode”?

I’ve linked the logs below. Too big to send as a file so I had to use Gdrive.

https://drive.google.com/file/d/1ZuFYdYq8bKyw41E4JLkppCERc2SoqZfT/view?usp=sharing

It happened at 18:38, 18:46, 18:52, 19:11, 19:16.

I have forwarded this to devteam@adguard.com as per your request.

**Comment by Aydinv13** [comment]
Thanks for your logs.
Updated your comment due to privacy reasons.

**Comment by SkyRexHUN** [comment]
Thank you.

**Comment by SkyRexHUN** [comment]
Additional info: pings are all over the place in the Windows client, switched to the browser extension for now.
For example: No servers under 150ms in Windows, but in the browser extension (and iOS) the fastest servers are around 30ms.

**Comment by adbuker** [comment]
@SkyRexHUN , could you please check the issue with the latest nightly build we've published on last Friday

**Comment by SkyRexHUN** [comment]
I downloaded the client, but currently my ISP is experiencing connection loss in my area, so I am waiting for them to fix the issues because each and every VPN server's ping is over 500ms right now for me.

**Comment by adbuker** [comment]
@SkyRexHUN, well, let's wait until the situation become normal

**Comment by SkyRexHUN** [comment]
@adbuker I've tested it today, I had normal pings (~30ms) for some servers, but the disconnect issue is still present, the app terminates my connection every 10 minutes.

**Comment by adbuker** [comment]
> @adbuker I've tested it today, I had normal pings (~30ms) for some servers, but the disconnect issue is still present, the app terminates my connection every 10 minutes.

Could you please enable debug logs, repro the issue and send the logs from %programdata%/AdguardVpn/logs

**Comment by SkyRexHUN** [comment]
> Could you please enable debug logs, repro the issue and send the logs from %programdata%/AdguardVpn/logs

Where should I send the logs?

**Comment by adbuker** [comment]
> > Could you please enable debug logs, repro the issue and send the logs from %programdata%/AdguardVpn/logs
> 
> Where should I send the logs?

please send to the devteam@adguard.com with the reference to this issue

**Comment by SkyRexHUN** [comment]
> please send to the [devteam@adguard.com](mailto:devteam@adguard.com) with the reference to this issue

Done, please check your inbox.

**Comment by adbuker** [comment]
@SkyRexHUN , according to your logs there weren't any connect/disconnect cycles in fact. Btw, have you faced any signs of connection interrupts and reconnects, except the described above, e.g. "yellow" icon in the tray menu). Frankly, I guess you faced the notification queue in the Windows notifications center. Could you please click on the "Action Center" icon, then click "Clear all notifications" above your "Quick Actions" and all notification will be erased. If the issue still remains, could you please provide me the remote access via AnyDesk app (of course, all the credentials please send to the [devteam@adguard.com](mailto:devteam@adguard.com) for the securityness) in order to check the issue first-hand.

**Comment by SkyRexHUN** [comment]
Yes, the notification center has lots of entries about every 10 minutes from AdGuard VPN, but when those happen, websites temporarily do not load when using a web browser. They usually work after waiting at least 30 seconds or so. I will provide AnyDesk access via email.

**Comment by SkyRexHUN** [comment]
Okay I did some further research with the VPN on, and the reconnects happen when the router has a stroke or smth. Since this happens randomly I used a network monitor tool to catch what happens. When this happens, pings to all servers went well over 200 ms, so it makes me thing that makes reaching the VPN servers unreachable as well.

Net Uptime Monitor Failure Log (NetUptimeMonitor.com)
UNLICENSED TRIAL VERSION
 
=======================================
2022. 06. 20. 16:50:38	Log Start
Ping Target 1: 8.8.8.8 - Google
Ping Target 2: 4.2.2.2 - Level3
Ping Target 3: 1.1.1.1 - Cloudflare
Wait for Ping (milliseconds): 200
Test Interval (seconds): 5
Log Failure Longer Than (seconds): 5
---------------------------------------
Failure Start      	Length
-------------      	------
2022. 06. 20. 16:53:01	0:00:05
LAN Failed - No router response

2022. 06. 20. 16:53:20	0:00:08
LAN Failed - No router response

---------------------------------------
2022. 06. 20. 17:37:41	Log End
Monitor Duration	0:47:00
Failure Summary:
	Count		2
	Total Downtime	0:00:13
	% Downtime	0.49
	Minimum Length	0:00:05
	Maximum Length	0:00:08
	Average Length	0:00:06
=======================================

**Comment by SkyRexHUN** [comment]
Okay I think this is definitely an ISP side issue, so I will close this ticket now, but I have some other bugs with the beta so I might open another one soon.
